# Basic dependabot.yml file with
# minimum configuration for nuget
# https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-dependencies-updated-automatically

version: 2
updates:
  - package-ecosystem: nuget
    directory: /source
    schedule:
      interval: weekly
    groups:
      # Group patch/minor updates in same PR. Major updates is not in the group, so they will all have separate PR's.
      # See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/optimizing-pr-creation-version-updates
      # and https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#groups--
      minor-or-patch:
        applies-to: version-updates
        patterns:
          - "*" # Matches all package names
        update-types:
          - minor
          - patch

