# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: CI orchestrator (mono-repo)

on:
  pull_request:
    branches:
      - main

jobs:
  #
  # License and Markdown Check
  #
  ci_base:
    uses: Energinet-DataHub/.github/.github/workflows/ci-base.yml@v14
    with:
      skip_yaml_lint: true  # TODO: Remove before merge
    secrets:
      dh3serviceaccount_privatekey: ${{ secrets.dh3serviceaccount_privatekey }}

  #
  # Detect changes to start relevant workflows
  #
  changes:
    uses: ./.github/workflows/detect-changes.yml
    with:
      print_debug_output: 'true'  # TODO: Remove before merge
      solution_file: 'source/ProcessManager.sln'
      # Hostnames = famous mountains
      hostnames: "
            {
              'everest': 'ProcessManager.csproj',
              'montblanc': 'ProcessManager.Orchestrations.csproj',
              'dbmigrations': 'ProcessManager.DatabaseMigration.csproj'
            }"

  ci_processmanager_nuget:
    needs: changes
    if: ${{ needs.changes.outputs.processmanager_nuget == 'true' }}
    uses: ./.github/workflows/processmanager-client-bundle-publish.yml
    secrets: inherit

  ci_dotnet_everest:
    if: ${{ fromJson(needs.changes.outputs.job_context).everest == 'true' }}
    needs: changes
    uses: ./.github/workflows/ci-dotnet.yml
    with:
      release_name: process_manager_everest
      project_file: source/ProcessManager/ProcessManager.csproj

  ci_dotnet_montblanc:
    if: ${{ fromJson(needs.changes.outputs.job_context).montblanc == 'true' }}
    needs: changes
    uses: ./.github/workflows/ci-dotnet.yml
    with:
      release_name: process_manager_montblanc
      project_file: source/ProcessManager/ProcessManager.csproj

  ci_dotnet_dbmigrations:
    if: ${{ fromJson(needs.changes.outputs.job_context).dbmigrations == 'true' }}
    needs: changes
    uses: ./.github/workflows/ci-dotnet.yml
    with:
      release_name: process_manager_dbmigrations
      project_file: source/ProcessManager.DatabaseMigration/ProcessManager.DatabaseMigration.csproj

  ci_run_tests:
    needs: changes
    uses: ./.github/workflows/ci-dotnet-runtests.yml
    with:
      print_debug_output: 'true'  # TODO: Remove before merge
      affected_changes: ${{ needs.changes.outputs.affected_changes }}

  #
  # Branch policy status check
  #

  allow_merge_ci_orchestrator:
    runs-on: ubuntu-latest
    needs:
      [
        ci_base,
        changes,
        ci_dotnet_everest,
        ci_dotnet_montblanc,
        ci_dotnet_dbmigrations,
        ci_run_tests
      ]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"
          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
